services:
  mysql:
    image: mysql:8.0.36
    container_name: shop-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"   # ⚠ 로컬 충돌 방지용
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shoppw
      TZ: Asia/Seoul
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --default-time-zone=+09:00
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro

volumes:
  mysql_data: